// Mock data for Hule AI Recruitment Platform

export interface Job {
  id: string;
  title: string;
  department: string;
  location: string;
  type: "full-time" | "part-time" | "contract";
  level: string;
  status: "active" | "paused" | "closed" | "draft";
  headcount: number;
  applied: number;
  shortlisted: number;
  interviewed: number;
  createdAt: string;
  updatedAt: string;
  description?: string;
  requirements?: string[];
  skills?: string[];
  salary?: string;
  aiScore?: number;
}

export interface WorkHistory {
  title: string;
  company: string;
  period: string;
  description: string;
}

export interface EducationHistory {
  school: string;
  major: string;
  degree: string;
  period: string;
}

export interface InterviewRecord {
  round: string;
  date: string;
  interviewer: string;
  result: "pass" | "fail" | "pending";
  feedback?: string;
  score?: number;
}

export interface Candidate {
  id: string;
  name: string;
  email: string;
  phone?: string;
  currentTitle: string;
  currentCompany: string;
  experience: number;
  education: string;
  location: string;
  jobId: string;
  jobTitle: string;
  status: "new" | "screening" | "interview" | "offer" | "hired" | "rejected";
  aiScore: number;
  aiScoreDetails: {
    coreSkills: number;
    businessMatch: number;
    projectComplexity: number;
    levelMatch: number;
    growthPotential: number;
    stability: number;
  };
  dimensions: Record<string, number>;
  evidence?: Record<string, string[]>;
  tags: string[];
  riskTags?: string[];
  recommendation: "strong_yes" | "yes" | "maybe" | "no";
  summary?: string;
  aiConclusion?: string;
  strengths?: string[];
  weaknesses?: string[];
  appliedAt: string;
  resumeUrl?: string;
  avatar?: string;
  manualScore?: number;
  manualNote?: string;
  skills?: string[];
  workHistory?: WorkHistory[];
  educationHistory?: EducationHistory[];
  interviews?: InterviewRecord[];
}

export interface Interview {
  id: string;
  candidateId: string;
  candidateName: string;
  jobId: string;
  jobTitle: string;
  round: number;
  roundName: string;
  status: "scheduled" | "completed" | "cancelled" | "pending";
  scheduledAt: string;
  duration?: number;
  interviewers: string[];
  type: "online" | "onsite" | "phone";
  score?: number;
  feedback?: string;
  questions?: InterviewQuestion[];
}

export interface InterviewQuestion {
  id: string;
  type: "basic" | "deep" | "reverse" | "risk" | "management" | "business";
  question: string;
  dimension: string;
  answer?: string;
  score?: number;
}

export interface Skill {
  id: string;
  name: string;
  description: string;
  type: "official" | "team" | "personal";
  category: string;
  usageCount: number;
  accuracy?: number;
  status: "published" | "draft" | "reviewing";
  author: string;
  createdAt: string;
  tags: string[];
  isApplied?: boolean;
  icon?: string;
}

// Mock Jobs
export const mockJobs: Job[] = [
  {
    id: "job-001",
    title: "高级AI产品经理",
    department: "产品部",
    location: "北京",
    type: "full-time",
    level: "P7",
    status: "active",
    headcount: 2,
    applied: 48,
    shortlisted: 12,
    interviewed: 6,
    createdAt: "2024-03-01",
    updatedAt: "2024-03-15",
    skills: ["产品规划", "AI/ML", "数据分析", "用户研究", "敏捷开发"],
    salary: "30-50K",
    aiScore: 92,
    description: "负责AI产品线的规划与落地，推动AI能力在产品中的深度应用。",
    requirements: [
      "5年以上产品经理经验",
      "有AI/ML产品经验优先",
      "强数据分析能力",
      "优秀的跨部门协作能力",
    ],
  },
  {
    id: "job-002",
    title: "机器学习工程师",
    department: "技术部",
    location: "上海",
    type: "full-time",
    level: "P6",
    status: "active",
    headcount: 3,
    applied: 73,
    shortlisted: 18,
    interviewed: 8,
    createdAt: "2024-02-20",
    updatedAt: "2024-03-10",
    skills: ["Python", "PyTorch", "NLP", "推荐系统", "大模型"],
    salary: "35-60K",
    aiScore: 88,
    description: "负责核心算法研发，推动大模型在招聘场景的落地应用。",
    requirements: [
      "3年以上ML工程师经验",
      "熟悉PyTorch/TensorFlow",
      "有NLP项目经验",
      "计算机相关专业硕士及以上",
    ],
  },
  {
    id: "job-003",
    title: "HRBP",
    department: "人力资源部",
    location: "北京",
    type: "full-time",
    level: "P5",
    status: "active",
    headcount: 1,
    applied: 31,
    shortlisted: 8,
    interviewed: 4,
    createdAt: "2024-03-05",
    updatedAt: "2024-03-18",
    skills: ["招聘管理", "员工关系", "组织发展", "数据分析"],
    salary: "20-35K",
    aiScore: 85,
    description: "支持业务部门的人才招募与员工发展，推动HR数字化转型。",
    requirements: [
      "3年以上HRBP经验",
      "熟悉互联网行业",
      "有招聘系统使用经验",
      "优秀的沟通协调能力",
    ],
  },
  {
    id: "job-004",
    title: "前端工程师",
    department: "技术部",
    location: "深圳",
    type: "full-time",
    level: "P5",
    status: "active",
    headcount: 2,
    applied: 56,
    shortlisted: 14,
    interviewed: 5,
    createdAt: "2024-02-28",
    updatedAt: "2024-03-12",
    skills: ["React", "TypeScript", "Next.js", "性能优化", "设计系统"],
    salary: "25-45K",
    aiScore: 90,
  },
  {
    id: "job-005",
    title: "数据分析师",
    department: "数据部",
    location: "北京",
    type: "full-time",
    level: "P5",
    status: "paused",
    headcount: 1,
    applied: 22,
    shortlisted: 5,
    interviewed: 2,
    createdAt: "2024-01-15",
    updatedAt: "2024-02-20",
    skills: ["SQL", "Python", "数据可视化", "A/B测试", "商业分析"],
    salary: "20-35K",
    aiScore: 78,
  },
];

// Mock Candidates
export const mockCandidates: Candidate[] = [
  {
    id: "cand-001",
    name: "李明远",
    email: "liming@example.com",
    phone: "138****8888",
    currentTitle: "高级产品经理",
    currentCompany: "字节跳动",
    experience: 6,
    education: "北京大学 · 计算机科学 · 硕士",
    location: "北京",
    jobId: "job-001",
    jobTitle: "高级AI产品经理",
    status: "interview",
    aiScore: 91,
    aiScoreDetails: {
      coreSkills: 92,
      businessMatch: 88,
      projectComplexity: 90,
      levelMatch: 95,
      growthPotential: 87,
      stability: 82,
    },
    tags: ["AI产品", "数据驱动", "跨部门协作", "大厂背景"],
    riskTags: ["跳槽频率偏高"],
    recommendation: "strong_yes",
    summary: "具备扎实的AI产品经验，在字节跳动主导过多个亿级用户产品的AI化改造，数据分析能力突出，与岗位高度匹配。",
    aiConclusion: "李明远在字节跳动担任高级产品经理6年，主导过今日头条、抖音等亿级用户产品的AI推荐系统改造，核心技能与岗位高度匹配。数据分析能力突出，曾通过A/B测试将推荐点击率提升23%。主要风险在于跳槽频率偏高（3年3家），建议在面试中重点探讨职业规划稳定性。综合评估：强烈推荐进入终面。",
    dimensions: { coreSkill: 92, businessMatch: 88, projectComplexity: 90, levelMatch: 95, growthPotential: 87, stability: 72 },
    evidence: {
      coreSkill: ["主导今日头条推荐系统AI化改造，DAU提升15%", "具备Python数据分析能力，熟悉ML产品化流程", "发表过2篇AI产品设计相关文章"],
      businessMatch: ["6年互联网产品经验，与岗位要求高度吻合", "有AI/ML产品从0到1的完整经历"],
      stability: ["3年内换了3家公司，平均在职时长约1年", "需要在面试中确认离职原因"]
    },
    strengths: ["AI产品规划经验丰富", "数据分析能力强", "有大规模团队协作经验"],
    weaknesses: ["跳槽频率略高（3年3家）", "管理经验相对有限"],
    skills: ["AI产品规划", "数据分析", "用户研究", "A/B测试", "Python", "跨部门协作"],
    workHistory: [
      { title: "高级产品经理", company: "字节跳动", period: "2021.06 - 至今", description: "负责今日头条推荐系统AI化改造，主导多个亿级用户产品的AI功能落地，通过A/B测试将推荐点击率提升23%。" },
      { title: "产品经理", company: "快手", period: "2020.03 - 2021.05", description: "负责短视频推荐算法产品化，与算法团队协作推动模型迭代，用户留存率提升18%。" },
      { title: "产品经理", company: "百度", period: "2018.07 - 2020.02", description: "参与搜索推荐产品设计，负责用户行为分析和产品迭代。" }
    ],
    educationHistory: [
      { school: "北京大学", major: "计算机科学", degree: "硕士", period: "2016 - 2018" },
      { school: "北京航空航天大学", major: "软件工程", degree: "本科", period: "2012 - 2016" }
    ],
    interviews: [
      { round: "HR初面", date: "2024-03-15", interviewer: "张晓雯", result: "pass", score: 88, feedback: "候选人表达清晰，AI产品经验丰富，对行业趋势有深刻理解。建议进入技术面。" }
    ],
    appliedAt: "2024-03-10",
  },
  {
    id: "cand-002",
    name: "王晓婷",
    email: "wangxt@example.com",
    currentTitle: "产品总监",
    currentCompany: "美团",
    experience: 8,
    education: "清华大学 · 工业工程 · 硕士",
    location: "北京",
    jobId: "job-001",
    jobTitle: "高级AI产品经理",
    status: "interview",
    aiScore: 87,
    aiScoreDetails: {
      coreSkills: 85,
      businessMatch: 90,
      projectComplexity: 88,
      levelMatch: 80,
      growthPotential: 92,
      stability: 95,
    },
    tags: ["战略思维", "团队管理", "业务增长", "O2O"],
    riskTags: ["AI专项经验偏少"],
    recommendation: "yes",
    summary: "管理经验丰富，业务理解深刻，但AI专项经验相对不足，需要在面试中重点验证AI能力。",
    aiConclusion: "王晓婷在美团担任产品总监8年，管理过15人产品团队，业务增长思维强，稳定性高。但AI专项经验相对不足，主要经验集中在O2O业务。建议在技术面重点验证其AI能力学习意愿和技术理解深度。综合评估：推荐进入下一轮。",
    dimensions: { coreSkill: 85, businessMatch: 90, projectComplexity: 88, levelMatch: 80, growthPotential: 92, stability: 95 },
    evidence: {
      businessMatch: ["8年互联网产品经验，业务理解深刻", "主导美团外卖增长产品，GMV提升40%"],
      coreSkill: ["AI专项经验相对不足，主要经验在O2O业务", "有数据分析经验但缺少ML产品化实践"]
    },
    strengths: ["管理经验丰富", "业务增长思维强", "稳定性高"],
    weaknesses: ["AI/ML专项经验不足", "技术背景相对薄弱"],
    skills: ["产品管理", "业务增长", "团队管理", "数据分析", "O2O产品"],
    workHistory: [
      { title: "产品总监", company: "美团", period: "2016.03 - 至今", description: "负责美团外卖增长产品线，管理15人产品团队，主导GMV提升40%的增长项目。" }
    ],
    educationHistory: [
      { school: "清华大学", major: "工业工程", degree: "硕士", period: "2014 - 2016" }
    ],
    interviews: [],
    appliedAt: "2024-03-08",
  },
  {
    id: "cand-003",
    name: "张宇轩",
    email: "zhangyx@example.com",
    currentTitle: "ML工程师",
    currentCompany: "阿里巴巴",
    experience: 4,
    education: "上海交通大学 · 人工智能 · 硕士",
    location: "上海",
    jobId: "job-002",
    jobTitle: "机器学习工程师",
    status: "screening",
    aiScore: 94,
    aiScoreDetails: {
      coreSkills: 96,
      businessMatch: 92,
      projectComplexity: 95,
      levelMatch: 90,
      growthPotential: 94,
      stability: 88,
    },
    tags: ["NLP", "大模型", "PyTorch", "推荐系统", "高潜力"],
    recommendation: "strong_yes",
    summary: "技术能力顶尖，在阿里主导了多个NLP和推荐系统项目，与岗位要求高度契合，是强推候选人。",
    aiConclusion: "张宇轩在阿里巴巴担任ML工程师4年，主导了多个NLP和推荐系统项目，技术能力顶尖。熟悉PyTorch、大模型微调等核心技术，与岗位要求高度契合。综合评估：强烈推荐，建议优先安排面试。",
    dimensions: { coreSkill: 96, businessMatch: 92, projectComplexity: 95, levelMatch: 90, growthPotential: 94, stability: 88 },
    evidence: {
      coreSkill: ["主导阿里NLP平台建设，服务10+业务线", "熟悉PyTorch、Transformer架构", "有大模型微调实战经验"]
    },
    strengths: ["核心技术能力突出", "大模型实战经验丰富", "项目复杂度高"],
    weaknesses: ["业务理解有待加强", "沟通表达需要验证"],
    skills: ["Python", "PyTorch", "NLP", "大模型", "推荐系统", "Transformer"],
    workHistory: [
      { title: "ML工程师", company: "阿里巴巴", period: "2020.07 - 至今", description: "负责NLP平台建设，主导大模型微调项目，服务10+业务线。" }
    ],
    educationHistory: [
      { school: "上海交通大学", major: "人工智能", degree: "硕士", period: "2018 - 2020" }
    ],
    interviews: [],
    appliedAt: "2024-03-12",
  },
  {
    id: "cand-004",
    name: "陈思雨",
    email: "chensy@example.com",
    currentTitle: "算法工程师",
    currentCompany: "腾讯",
    experience: 3,
    education: "浙江大学 · 计算机科学 · 硕士",
    location: "深圳",
    jobId: "job-002",
    jobTitle: "机器学习工程师",
    status: "screening",
    aiScore: 82,
    aiScoreDetails: {
      coreSkills: 85,
      businessMatch: 78,
      projectComplexity: 80,
      levelMatch: 88,
      growthPotential: 90,
      stability: 85,
    },
    tags: ["计算机视觉", "深度学习", "腾讯背景"],
    riskTags: ["NLP经验较少"],
    recommendation: "yes",
    summary: "技术基础扎实，但主要经验在CV方向，NLP经验相对不足，需要评估转型意愿和学习能力。",
    aiConclusion: "陈思雨技术基础扎实，腾讯3年CV方向经验，但NLP经验相对不足。建议在面试中重点评估其转型意愿和学习能力。综合评估：推荐，需要面试验证。",
    dimensions: { coreSkill: 85, businessMatch: 78, projectComplexity: 80, levelMatch: 88, growthPotential: 90, stability: 85 },
    evidence: {
      coreSkill: ["腾讯CV方向3年经验，技术基础扎实", "NLP项目经验较少，需要评估转型意愿"]
    },
    strengths: ["技术基础扎实", "学习能力强", "腾讯大厂经验"],
    weaknesses: ["NLP经验不足", "主方向与岗位有偏差"],
    skills: ["Python", "PyTorch", "计算机视觉", "深度学习", "TensorFlow"],
    workHistory: [
      { title: "算法工程师", company: "腾讯", period: "2021.07 - 至今", description: "负责CV算法研发，主导人脸识别和目标检测项目。" }
    ],
    educationHistory: [
      { school: "浙江大学", major: "计算机科学", degree: "硕士", period: "2019 - 2021" }
    ],
    interviews: [],
    appliedAt: "2024-03-11",
  },
  {
    id: "cand-005",
    name: "刘佳琪",
    email: "liujq@example.com",
    currentTitle: "HRBP",
    currentCompany: "滴滴",
    experience: 5,
    education: "中国人民大学 · 人力资源管理 · 本科",
    location: "北京",
    jobId: "job-003",
    jobTitle: "HRBP",
    status: "offer",
    aiScore: 89,
    aiScoreDetails: {
      coreSkills: 90,
      businessMatch: 88,
      projectComplexity: 85,
      levelMatch: 92,
      growthPotential: 86,
      stability: 90,
    },
    tags: ["招聘管理", "员工关系", "互联网经验", "数据分析"],
    recommendation: "strong_yes",
    summary: "HRBP经验丰富，在滴滴负责过技术团队的全流程招聘，熟悉互联网行业，与岗位高度匹配。",
    aiConclusion: "刘佳琪在滴滴担任HRBP 5年，负责技术团队全流程招聘，熟悉互联网行业招聘节奏，数据驱动思维强。与岗位高度匹配，综合评估：强烈推荐。",
    dimensions: { coreSkill: 90, businessMatch: 88, projectComplexity: 85, levelMatch: 92, growthPotential: 86, stability: 90 },
    evidence: {
      coreSkill: ["5年HRBP经验，负责过500人规模技术团队招聘", "熟悉互联网行业招聘节奏和候选人市场"]
    },
    strengths: ["HRBP经验丰富", "互联网行业背景", "数据驱动思维"],
    weaknesses: ["HR数字化工具使用经验有限"],
    skills: ["招聘管理", "员工关系", "组织发展", "数据分析", "HRIS系统"],
    workHistory: [
      { title: "HRBP", company: "滴滴出行", period: "2019.03 - 至今", description: "负责技术团队全流程招聘，管理500人规模团队的HR事务，推动HR数字化转型。" }
    ],
    educationHistory: [
      { school: "中国人民大学", major: "人力资源管理", degree: "本科", period: "2015 - 2019" }
    ],
    interviews: [
      { round: "HR初面", date: "2024-03-10", interviewer: "张晓雯", result: "pass", score: 90, feedback: "候选人经验丰富，与岗位高度匹配。" },
      { round: "业务面", date: "2024-03-15", interviewer: "部门总监", result: "pass", score: 88, feedback: "业务理解深刻，推荐进入终面。" }
    ],
    appliedAt: "2024-03-05",
  },
  {
    id: "cand-006",
    name: "赵鹏飞",
    email: "zhaopf@example.com",
    currentTitle: "前端架构师",
    currentCompany: "网易",
    experience: 7,
    education: "华中科技大学 · 软件工程 · 本科",
    location: "广州",
    jobId: "job-004",
    jobTitle: "前端工程师",
    status: "new",
    aiScore: 76,
    aiScoreDetails: {
      coreSkills: 88,
      businessMatch: 70,
      projectComplexity: 82,
      levelMatch: 65,
      growthPotential: 72,
      stability: 80,
    },
    tags: ["React", "架构设计", "性能优化"],
    riskTags: ["级别偏高", "薪资期望可能超出范围"],
    recommendation: "maybe",
    summary: "技术能力强，但当前级别偏高，薪资期望可能超出岗位范围，需要在面试中确认期望和意愿。",
    aiConclusion: "赵鹏飞技术能力强，但当前级别（前端架构师）与岗位（P5前端工程师）存在明显落差，薪资期望可能超出范围。建议在初面中直接确认薪资期望和降级意愿。综合评估：待定，需要面试确认。",
    dimensions: { coreSkill: 88, businessMatch: 70, projectComplexity: 82, levelMatch: 65, growthPotential: 72, stability: 80 },
    evidence: {
      levelMatch: ["当前职级为前端架构师，岗位要求P5，存在明显落差", "薪资期望可能超出岗位范围"]
    },
    strengths: ["技术能力突出", "架构经验丰富"],
    weaknesses: ["级别与岗位不匹配", "薪资期望风险"],
    skills: ["React", "TypeScript", "架构设计", "性能优化", "工程化"],
    workHistory: [
      { title: "前端架构师", company: "网易", period: "2017.03 - 至今", description: "负责前端架构设计，主导设计系统建设，推动前端工程化实践。" }
    ],
    educationHistory: [
      { school: "华中科技大学", major: "软件工程", degree: "本科", period: "2013 - 2017" }
    ],
    interviews: [],
    appliedAt: "2024-03-14",
  },
];

// Mock Interviews
export const mockInterviews: Interview[] = [
  {
    id: "int-001",
    candidateId: "cand-001",
    candidateName: "李明远",
    jobId: "job-001",
    jobTitle: "高级AI产品经理",
    round: 1,
    roundName: "HR初面",
    status: "completed",
    scheduledAt: "2024-03-15 14:00",
    duration: 60,
    interviewers: ["张晓雯"],
    type: "online",
    score: 88,
    feedback: "候选人表达清晰，AI产品经验丰富，对行业趋势有深刻理解。建议进入技术面。",
  },
  {
    id: "int-002",
    candidateId: "cand-001",
    candidateName: "李明远",
    jobId: "job-001",
    jobTitle: "高级AI产品经理",
    round: 2,
    roundName: "技术面",
    status: "scheduled",
    scheduledAt: "2024-03-20 15:00",
    interviewers: ["王工", "李总监"],
    type: "online",
  },
  {
    id: "int-003",
    candidateId: "cand-002",
    candidateName: "王晓婷",
    jobId: "job-001",
    jobTitle: "高级AI产品经理",
    round: 1,
    roundName: "HR初面",
    status: "completed",
    scheduledAt: "2024-03-14 10:00",
    duration: 45,
    interviewers: ["张晓雯"],
    type: "online",
    score: 82,
    feedback: "管理经验丰富，但AI专项能力需要进一步验证。",
  },
  {
    id: "int-004",
    candidateId: "cand-005",
    candidateName: "刘佳琪",
    jobId: "job-003",
    jobTitle: "HRBP",
    round: 3,
    roundName: "终面",
    status: "scheduled",
    scheduledAt: "2024-03-21 11:00",
    interviewers: ["HRD陈总"],
    type: "onsite",
  },
];

// Mock Skills
export const mockSkills: Skill[] = [
  // ===== 招聘全链路 (14个) - 官方技能包 =====
  {
    id: "skill-r01",
    name: "战略性岗位描述生成",
    description: "吸引顶尖人才的 JD 营销工具，结合岗位战略定位、市场竞争力和雇主品牌，生成高转化率职位描述。",
    type: "official",
    category: "招聘全链路",
    usageCount: 3842,
    accuracy: 92,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["JD生成", "雇主品牌", "官方认证"],
    icon: "📝",
  },
  {
    id: "skill-r02",
    name: "智能简历深度评估",
    description: "五维量化 + 引用原文 + 推荐等级，从技能匹配、经验深度、项目复杂度、成长轨迹、文化契合度五个维度全面评估候选人。",
    type: "official",
    category: "招聘全链路",
    usageCount: 5621,
    accuracy: 91,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["简历评估", "五维量化", "官方认证"],
    icon: "📊",
  },
  {
    id: "skill-r03",
    name: "深度面试题库生成",
    description: "真正区分候选人能力层次，基于岗位 JD 和候选人简历自动生成结构化面试题，覆盖基础、深度、行为、情景四类题型。",
    type: "official",
    category: "招聘全链路",
    usageCount: 4103,
    accuracy: 89,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["面试题库", "结构化面试", "官方认证"],
    icon: "❓",
  },
  {
    id: "skill-r04",
    name: "视频面试综合评估",
    description: "多维客观评分 + 录用建议，分析面试录像中的语言表达、逻辑思维、专业深度和非语言信号，输出结构化评估报告。",
    type: "official",
    category: "招聘全链路",
    usageCount: 2187,
    accuracy: 85,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["视频面试", "AI评分", "官方认证"],
    icon: "🎥",
  },
  {
    id: "skill-r05",
    name: "精准人才寻访战略",
    description: "渠道矩阵 + 话术 + 人才地图，为特定岗位制定主动寻访策略，包括目标人才画像、渠道优先级和接触话术模板。",
    type: "official",
    category: "招聘全链路",
    usageCount: 1456,
    accuracy: 83,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["人才寻访", "猎头策略", "官方认证"],
    icon: "🎯",
  },
  {
    id: "skill-r06",
    name: "Offer 设计与谈判",
    description: "薪酬结构 + 多场景谈判话术，根据候选人期望、市场数据和公司预算设计有竞争力的 Offer 方案，提供谈判策略和话术。",
    type: "official",
    category: "招聘全链路",
    usageCount: 2034,
    accuracy: 88,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["Offer谈判", "薪酬设计", "官方认证"],
    icon: "💼",
  },
  {
    id: "skill-r07",
    name: "新员工 Onboarding 体系",
    description: "90 天融入计划 + 风险预警，为新员工设计个性化入职路径，包含关键节点任务、融入评估和早期流失风险预警机制。",
    type: "official",
    category: "招聘全链路",
    usageCount: 1789,
    accuracy: 86,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["Onboarding", "入职管理", "官方认证"],
    icon: "🚀",
  },
  {
    id: "skill-r08",
    name: "候选人背景调查方案",
    description: "核查框架 + 问题设计 + 风险评级，系统化背调方案，覆盖学历核实、工作经历、离职原因、绩效表现和职业诚信等维度。",
    type: "official",
    category: "招聘全链路",
    usageCount: 1234,
    accuracy: 90,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["背景调查", "风险评级", "官方认证"],
    icon: "🔍",
  },
  {
    id: "skill-r09",
    name: "雇主品牌内容策划",
    description: "差异化定位 + 多渠道内容矩阵，帮助企业打造独特雇主品牌，制定 LinkedIn、招聘网站、社交媒体的内容发布策略。",
    type: "official",
    category: "招聘全链路",
    usageCount: 987,
    accuracy: 82,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["雇主品牌", "内容营销", "官方认证"],
    icon: "🌟",
  },
  {
    id: "skill-r10",
    name: "面试官标准化培训",
    description: "结构化面试体系 + 偏见规避 + 评分标准，为面试官提供系统培训方案，确保评估一致性和公平性，降低主观偏见影响。",
    type: "official",
    category: "招聘全链路",
    usageCount: 1567,
    accuracy: 87,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["面试官培训", "结构化面试", "官方认证"],
    icon: "👨‍🏫",
  },
  {
    id: "skill-r11",
    name: "招聘渠道 ROI 分析",
    description: "到岗成本 + 渠道效能矩阵 + 预算优化，量化分析各招聘渠道的投入产出比，优化招聘预算分配，提升整体招聘效率。",
    type: "official",
    category: "招聘全链路",
    usageCount: 876,
    accuracy: 91,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["渠道分析", "ROI", "官方认证"],
    icon: "📈",
  },
  {
    id: "skill-r12",
    name: "校园招聘全案设计",
    description: "目标院校矩阵 + 宣讲会方案 + 批量面试管理，为校园招聘季提供完整解决方案，从院校选择到批量评估全流程覆盖。",
    type: "official",
    category: "招聘全链路",
    usageCount: 1123,
    accuracy: 85,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["校园招聘", "批量面试", "官方认证"],
    icon: "🎓",
  },
  {
    id: "skill-r13",
    name: "猎头合作管理体系",
    description: "猎头评估标准 + 费用谈判 + KPI 考核，建立猎头合作管理体系，优化猎头筛选、合作协议和绩效考核机制。",
    type: "official",
    category: "招聘全链路",
    usageCount: 654,
    accuracy: 83,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["猎头管理", "外部合作", "官方认证"],
    icon: "🤝",
  },
  {
    id: "skill-r14",
    name: "候选人体验优化",
    description: "旅程地图 + 体验断点识别 + NPS 调研设计，系统优化候选人从投递到入职的全流程体验，提升雇主品牌吸引力。",
    type: "official",
    category: "招聘全链路",
    usageCount: 789,
    accuracy: 84,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["候选人体验", "NPS", "官方认证"],
    icon: "😊",
  },

  // ===== 人才管理 (14个) - 官方技能包 =====
  {
    id: "skill-m01",
    name: "360° 述职深度评估",
    description: "多维度述职评估框架，整合上级、平级、下级和自评视角，生成客观全面的绩效评估报告和发展建议。",
    type: "official",
    category: "人才管理",
    usageCount: 2341,
    accuracy: 88,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["360评估", "绩效管理", "官方认证"],
    icon: "🔄",
  },
  {
    id: "skill-m02",
    name: "战略目标 OKR 拆解",
    description: "将公司战略目标智能拆解为部门和个人 OKR，确保目标对齐和可衡量性，提供 OKR 质量评估和优化建议。",
    type: "official",
    category: "人才管理",
    usageCount: 1876,
    accuracy: 86,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["OKR", "目标管理", "官方认证"],
    icon: "🎯",
  },
  {
    id: "skill-m03",
    name: "高效 1on1 对话设计",
    description: "为管理者设计结构化 1on1 对话框架，包含议题准备、反馈技巧、目标跟进和员工发展讨论的完整指南。",
    type: "official",
    category: "人才管理",
    usageCount: 1543,
    accuracy: 87,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["1on1", "管理沟通", "官方认证"],
    icon: "💬",
  },
  {
    id: "skill-m04",
    name: "离职风险预警与保留",
    description: "基于员工行为数据、绩效趋势和市场薪酬分析，识别高离职风险员工，制定个性化保留方案和干预策略。",
    type: "official",
    category: "人才管理",
    usageCount: 1234,
    accuracy: 82,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["离职预警", "人才保留", "官方认证"],
    icon: "⚠️",
  },
  {
    id: "skill-m05",
    name: "个性化学习发展路径",
    description: "基于员工技能图谱、职业目标和岗位要求，生成个性化学习发展计划，推荐课程资源和实践项目。",
    type: "official",
    category: "人才管理",
    usageCount: 987,
    accuracy: 84,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["学习发展", "职业规划", "官方认证"],
    icon: "📚",
  },
  {
    id: "skill-m06",
    name: "人才盘点九宫格系统",
    description: "基于绩效和潜力双维度的人才盘点工具，自动生成九宫格分布图，识别明星员工、高潜人才和需要关注的群体。",
    type: "official",
    category: "人才管理",
    usageCount: 1456,
    accuracy: 89,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["人才盘点", "九宫格", "官方认证"],
    icon: "📋",
  },
  {
    id: "skill-m07",
    name: "团队能力矩阵分析",
    description: "可视化团队技能分布，识别能力缺口和冗余，为团队建设、招聘补充和培训投入提供数据支撑。",
    type: "official",
    category: "人才管理",
    usageCount: 1123,
    accuracy: 87,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["团队能力", "技能矩阵", "官方认证"],
    icon: "🗂️",
  },
  {
    id: "skill-m08",
    name: "关键岗位继任规划",
    description: "识别关键岗位风险，建立继任者候选池，制定继任者发展计划，确保关键岗位的人才连续性。",
    type: "official",
    category: "人才管理",
    usageCount: 876,
    accuracy: 85,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["继任规划", "关键岗位", "官方认证"],
    icon: "🏆",
  },
  {
    id: "skill-m09",
    name: "高潜人才识别模型",
    description: "通过成长轨迹、学习能力、项目挑战度等维度识别高潜力候选人，适用于校招和社招场景。",
    type: "official",
    category: "人才管理",
    usageCount: 1678,
    accuracy: 83,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["高潜人才", "成长性", "官方认证"],
    icon: "⭐",
  },
  {
    id: "skill-m10",
    name: "绩效改进计划（PIP）",
    description: "为绩效不达标员工制定结构化改进计划，设定明确目标、时间节点和支持措施，兼顾合规性和人文关怀。",
    type: "official",
    category: "人才管理",
    usageCount: 654,
    accuracy: 86,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["PIP", "绩效改进", "官方认证"],
    icon: "📈",
  },
  {
    id: "skill-m11",
    name: "晋升答辩材料准备",
    description: "帮助员工系统梳理晋升材料，包括成果量化、能力证明、发展规划，提升晋升答辩成功率。",
    type: "official",
    category: "人才管理",
    usageCount: 789,
    accuracy: 84,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["晋升管理", "职业发展", "官方认证"],
    icon: "🎖️",
  },
  {
    id: "skill-m12",
    name: "导师制度设计",
    description: "设计有效的导师制度，包括导师匹配算法、辅导计划模板、进度跟踪和效果评估机制。",
    type: "official",
    category: "人才管理",
    usageCount: 543,
    accuracy: 82,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["导师制度", "人才培养", "官方认证"],
    icon: "👥",
  },
  {
    id: "skill-m13",
    name: "职业发展对话框架",
    description: "为管理者提供职业发展对话指南，帮助员工明确职业目标、识别发展机会和制定行动计划。",
    type: "official",
    category: "人才管理",
    usageCount: 987,
    accuracy: 85,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["职业发展", "管理对话", "官方认证"],
    icon: "🗺️",
  },
  {
    id: "skill-m14",
    name: "核心人才保留方案",
    description: "针对核心人才制定个性化保留策略，综合薪酬、发展机会、文化认同和工作环境等多维度保留措施。",
    type: "official",
    category: "人才管理",
    usageCount: 1123,
    accuracy: 88,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["人才保留", "核心员工", "官方认证"],
    icon: "💎",
  },

  // ===== 组织与文化 (11个) - 官方技能包 =====
  {
    id: "skill-o01",
    name: "组织架构诊断优化",
    description: "分析现有组织架构的效率瓶颈、汇报关系和协作障碍，提供优化建议和变革路径规划。",
    type: "official",
    category: "组织与文化",
    usageCount: 876,
    accuracy: 84,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["组织架构", "效率优化", "官方认证"],
    icon: "🏢",
  },
  {
    id: "skill-o02",
    name: "员工体验调研设计",
    description: "设计科学的员工体验调研方案，包括问卷设计、数据分析和改进建议，提升员工满意度和敬业度。",
    type: "official",
    category: "组织与文化",
    usageCount: 1234,
    accuracy: 86,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["员工体验", "调研设计", "官方认证"],
    icon: "📊",
  },
  {
    id: "skill-o03",
    name: "薪酬竞争力诊断",
    description: "对标市场薪酬数据，诊断企业薪酬体系的竞争力，识别薪酬风险岗位，提供调薪策略建议。",
    type: "official",
    category: "组织与文化",
    usageCount: 987,
    accuracy: 89,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["薪酬诊断", "市场对标", "官方认证"],
    icon: "💰",
  },
  {
    id: "skill-o04",
    name: "跨部门协作优化",
    description: "识别跨部门协作障碍，设计协作流程和沟通机制，提升组织整体协同效率和项目交付质量。",
    type: "official",
    category: "组织与文化",
    usageCount: 765,
    accuracy: 83,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["跨部门协作", "流程优化", "官方认证"],
    icon: "🔗",
  },
  {
    id: "skill-o05",
    name: "企业文化建设行动计划",
    description: "基于企业战略和现有文化诊断，制定文化建设行动计划，包括文化宣导、行为标准和评估机制。",
    type: "official",
    category: "组织与文化",
    usageCount: 654,
    accuracy: 81,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["企业文化", "文化建设", "官方认证"],
    icon: "🌱",
  },
  {
    id: "skill-o06",
    name: "人力成本分析报告",
    description: "全面分析人力成本结构，识别成本优化空间，提供人效提升策略和预算规划建议。",
    type: "official",
    category: "组织与文化",
    usageCount: 876,
    accuracy: 90,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["人力成本", "成本优化", "官方认证"],
    icon: "📉",
  },
  {
    id: "skill-o07",
    name: "组织变革沟通方案",
    description: "为组织变革制定系统沟通方案，管理变革阻力，确保变革信息有效传达，提升变革成功率。",
    type: "official",
    category: "组织与文化",
    usageCount: 543,
    accuracy: 82,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["变革管理", "沟通方案", "官方认证"],
    icon: "🔄",
  },
  {
    id: "skill-o08",
    name: "HRBP 部门诊断报告",
    description: "对业务部门进行全面 HR 诊断，分析人才结构、能力缺口、管理效能，提供针对性改进建议。",
    type: "official",
    category: "组织与文化",
    usageCount: 987,
    accuracy: 87,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["HRBP", "部门诊断", "官方认证"],
    icon: "🏥",
  },
  {
    id: "skill-o09",
    name: "团队健康度评估",
    description: "评估团队的心理安全感、协作质量、目标清晰度和成员满意度，识别团队健康风险并提供干预建议。",
    type: "official",
    category: "组织与文化",
    usageCount: 1123,
    accuracy: 85,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["团队健康", "心理安全", "官方认证"],
    icon: "💚",
  },
  {
    id: "skill-o10",
    name: "远程/混合办公政策",
    description: "设计适合企业实际的远程和混合办公政策，包括工作规范、协作工具配置、绩效评估调整和文化维护策略。",
    type: "official",
    category: "组织与文化",
    usageCount: 876,
    accuracy: 83,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["远程办公", "混合办公", "官方认证"],
    icon: "🏠",
  },
  {
    id: "skill-o11",
    name: "DEI 现状评估与改善计划",
    description: "评估企业多元化、公平性和包容性现状，识别差距，制定可执行的 DEI 改善计划和衡量指标。",
    type: "official",
    category: "组织与文化",
    usageCount: 543,
    accuracy: 80,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["DEI", "多元包容", "官方认证"],
    icon: "🌈",
  },

  // ===== 合规文档 (9个) - 官方技能包 =====
  {
    id: "skill-c01",
    name: "劳动合同风险审查",
    description: "智能审查劳动合同条款，识别法律风险点，提供合规修改建议，确保合同符合最新劳动法规要求。",
    type: "official",
    category: "合规文档",
    usageCount: 2341,
    accuracy: 93,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["劳动合同", "法律合规", "官方认证"],
    icon: "⚖️",
  },
  {
    id: "skill-c02",
    name: "智能 HR 政策问答",
    description: "基于企业 HR 政策知识库，智能回答员工关于假期、福利、晋升、考勤等政策问题，提升 HR 服务效率。",
    type: "official",
    category: "合规文档",
    usageCount: 3456,
    accuracy: 91,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["HR政策", "智能问答", "官方认证"],
    icon: "💡",
  },
  {
    id: "skill-c03",
    name: "合规离职流程管理",
    description: "规范化离职流程管理，确保工作交接、资产归还、权限注销等环节合规完成，降低离职风险。",
    type: "official",
    category: "合规文档",
    usageCount: 1876,
    accuracy: 89,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["离职管理", "合规流程", "官方认证"],
    icon: "🚪",
  },
  {
    id: "skill-c04",
    name: "劳动争议应对方案",
    description: "提供劳动争议预防和应对策略，包括证据收集、调解技巧和仲裁准备，保护企业合法权益。",
    type: "official",
    category: "合规文档",
    usageCount: 987,
    accuracy: 88,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["劳动争议", "法律应对", "官方认证"],
    icon: "🛡️",
  },
  {
    id: "skill-c05",
    name: "HR 合规自查清单",
    description: "全面的 HR 合规自查工具，覆盖招聘、用工、薪酬、社保、离职等环节，帮助企业识别和消除合规风险。",
    type: "official",
    category: "合规文档",
    usageCount: 2134,
    accuracy: 92,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["合规自查", "风险管理", "官方认证"],
    icon: "✅",
  },
  {
    id: "skill-c06",
    name: "员工手册智能生成",
    description: "基于企业规模、行业特点和文化价值观，智能生成符合法规要求的员工手册，支持多版本定制。",
    type: "official",
    category: "合规文档",
    usageCount: 1567,
    accuracy: 87,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["员工手册", "制度建设", "官方认证"],
    icon: "📖",
  },
  {
    id: "skill-c07",
    name: "竞业限制协议审查",
    description: "审查竞业限制协议的合法性和合理性，评估执行风险，提供合规优化建议。",
    type: "official",
    category: "合规文档",
    usageCount: 876,
    accuracy: 90,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["竞业限制", "协议审查", "官方认证"],
    icon: "🔒",
  },
  {
    id: "skill-c08",
    name: "工伤处理合规指南",
    description: "提供工伤事故的合规处理流程，包括报告、认定、赔偿计算和预防措施，降低企业法律风险。",
    type: "official",
    category: "合规文档",
    usageCount: 654,
    accuracy: 91,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["工伤处理", "合规指南", "官方认证"],
    icon: "🏥",
  },
  {
    id: "skill-c09",
    name: "薪酬合规性审查",
    description: "审查薪酬体系的合规性，包括最低工资标准、加班费计算、社保缴纳基数等，确保薪酬发放合法合规。",
    type: "official",
    category: "合规文档",
    usageCount: 1234,
    accuracy: 93,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["薪酬合规", "法规审查", "官方认证"],
    icon: "💳",
  },

  // ===== 数据与洞察 (7个) - 官方技能包 =====
  {
    id: "skill-d01",
    name: "HR 数据分析报告",
    description: "整合多维度 HR 数据，生成可视化分析报告，揭示人才趋势、效率瓶颈和改进机会，支持数据驱动决策。",
    type: "official",
    category: "数据与洞察",
    usageCount: 2876,
    accuracy: 91,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["数据分析", "HR报告", "官方认证"],
    icon: "📊",
  },
  {
    id: "skill-d02",
    name: "招聘漏斗优化分析",
    description: "分析招聘各阶段转化率，识别漏斗瓶颈，提供针对性优化策略，提升整体招聘效率和质量。",
    type: "official",
    category: "数据与洞察",
    usageCount: 1987,
    accuracy: 89,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["招聘漏斗", "转化优化", "官方认证"],
    icon: "🔽",
  },
  {
    id: "skill-d03",
    name: "人才市场洞察报告",
    description: "实时分析目标岗位的人才供需状况、薪酬趋势和竞争格局，为招聘策略制定提供市场情报支持。",
    type: "official",
    category: "数据与洞察",
    usageCount: 1543,
    accuracy: 87,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["市场洞察", "人才趋势", "官方认证"],
    icon: "🌐",
  },
  {
    id: "skill-d04",
    name: "人力规划预测模型",
    description: "基于业务增长预测和历史人效数据，建立人力需求预测模型，支持年度人力规划和预算编制。",
    type: "official",
    category: "数据与洞察",
    usageCount: 876,
    accuracy: 85,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["人力规划", "预测模型", "官方认证"],
    icon: "🔮",
  },
  {
    id: "skill-d05",
    name: "离职数据深度分析",
    description: "深度分析离职数据，识别离职规律、高风险群体和根本原因，为人才保留策略提供数据支撑。",
    type: "official",
    category: "数据与洞察",
    usageCount: 1123,
    accuracy: 88,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["离职分析", "人才保留", "官方认证"],
    icon: "📉",
  },
  {
    id: "skill-d06",
    name: "薪酬带宽体系设计",
    description: "基于岗位价值评估和市场薪酬数据，设计科学的薪酬带宽体系，平衡内部公平性和外部竞争力。",
    type: "official",
    category: "数据与洞察",
    usageCount: 987,
    accuracy: 90,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["薪酬体系", "带宽设计", "官方认证"],
    icon: "💹",
  },
  {
    id: "skill-d07",
    name: "HR 年度述职报告",
    description: "智能生成 HR 年度述职报告，整合全年数据亮点、重点项目成果和来年规划，提升 HR 价值可见度。",
    type: "official",
    category: "数据与洞察",
    usageCount: 654,
    accuracy: 86,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["年度报告", "HR价值", "官方认证"],
    icon: "📋",
  },

  // ===== 图片识别 (2个) - 官方技能包 =====
  {
    id: "skill-i01",
    name: "简历照片专业分析",
    description: "AI 分析简历照片的专业形象，评估着装、表情、背景等要素，提供候选人第一印象参考。",
    type: "official",
    category: "图片识别",
    usageCount: 1234,
    accuracy: 78,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["图片识别", "简历分析", "官方认证"],
    icon: "📸",
  },
  {
    id: "skill-i02",
    name: "组织架构图智能解读",
    description: "自动识别和解析组织架构图，提取层级关系、汇报结构和部门信息，转化为结构化数据。",
    type: "official",
    category: "图片识别",
    usageCount: 876,
    accuracy: 82,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["图片识别", "组织架构", "官方认证"],
    icon: "🗺️",
  },

  // ===== AI 辅助决策 (3个) - 官方技能包 =====
  {
    id: "skill-a01",
    name: "录用决策辅助分析",
    description: "综合候选人评估数据、岗位要求和团队现状，生成录用决策辅助报告，支持多候选人横向对比和最终推荐。",
    type: "official",
    category: "AI辅助决策",
    usageCount: 2341,
    accuracy: 87,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["录用决策", "AI辅助", "官方认证"],
    icon: "🤖",
  },
  {
    id: "skill-a02",
    name: "薪酬谈判策略",
    description: "基于候选人期望、市场数据和公司预算，生成个性化薪酬谈判策略，提高 Offer 接受率。",
    type: "official",
    category: "AI辅助决策",
    usageCount: 1876,
    accuracy: 85,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["薪酬谈判", "Offer策略", "官方认证"],
    icon: "💬",
  },
  {
    id: "skill-a03",
    name: "HR 政策影响评估",
    description: "评估新 HR 政策对员工满意度、人才保留和组织效能的潜在影响，提供政策优化建议和实施风险预警。",
    type: "official",
    category: "AI辅助决策",
    usageCount: 987,
    accuracy: 83,
    status: "published",
    author: "葫乐官方",
    createdAt: "2024-01-01",
    tags: ["政策评估", "影响分析", "官方认证"],
    icon: "📋",
  },

  // ===== 自定义技能包（团队/个人，需要点击应用）=====
  {
    id: "skill-t01",
    name: "互联网HRBP综合评估",
    description: "针对互联网行业HRBP岗位的专项评估，重点考察招聘管理、员工关系和数字化工具使用能力。由团队根据实际业务场景定制。",
    type: "team",
    category: "招聘全链路",
    usageCount: 234,
    accuracy: 83,
    status: "published",
    author: "张晓雯",
    createdAt: "2024-02-15",
    tags: ["HRBP", "互联网", "团队共享"],
    isApplied: false,
    icon: "👥",
  },
  {
    id: "skill-t02",
    name: "高潜力候选人识别模型",
    description: "通过成长轨迹、学习能力、项目挑战度等维度识别高潜力候选人，适用于校招和社招。团队内部验证版本。",
    type: "team",
    category: "人才管理",
    usageCount: 567,
    accuracy: 79,
    status: "published",
    author: "李HR总监",
    createdAt: "2024-02-01",
    tags: ["高潜力", "成长性", "团队共享"],
    isApplied: true,
    icon: "⭐",
  },
  {
    id: "skill-p01",
    name: "前端工程师技术深度评估",
    description: "评估前端工程师的技术深度，包括框架原理、性能优化、工程化实践等维度。个人定制版本，仅自己可见。",
    type: "personal",
    category: "招聘全链路",
    usageCount: 45,
    status: "draft",
    author: "张晓雯",
    createdAt: "2024-03-10",
    tags: ["前端", "React", "个人"],
    isApplied: false,
    icon: "💻",
  },
  {
    id: "skill-p02",
    name: "AI算法工程师专项评估",
    description: "专为AI算法工程师设计的评估模型，重点考察大模型应用、算法创新和工程落地能力。个人实验版本。",
    type: "personal",
    category: "招聘全链路",
    usageCount: 12,
    status: "draft",
    author: "张晓雯",
    createdAt: "2024-03-20",
    tags: ["AI算法", "大模型", "个人"],
    isApplied: false,
    icon: "🧠",
  },
];

// Analytics data
export const analyticsData = {
  funnel: [
    { stage: "简历投递", count: 230, rate: 100 },
    { stage: "AI筛选通过", count: 87, rate: 37.8 },
    { stage: "HR初筛", count: 52, rate: 22.6 },
    { stage: "一面", count: 28, rate: 12.2 },
    { stage: "二面", count: 16, rate: 7.0 },
    { stage: "终面", count: 9, rate: 3.9 },
    { stage: "Offer", count: 6, rate: 2.6 },
  ],
  aiAdoptionRate: 73,
  manualCorrectionRate: 18,
  avgTimeToHire: 23,
  offerAcceptRate: 85,
  monthlyTrend: [
    { month: "10月", applications: 45, hires: 2 },
    { month: "11月", applications: 62, hires: 3 },
    { month: "12月", applications: 38, hires: 1 },
    { month: "1月", applications: 71, hires: 4 },
    { month: "2月", applications: 55, hires: 3 },
    { month: "3月", applications: 89, hires: 5 },
  ],
  skillHeatmap: [
    { skill: "Python", demand: 92, supply: 78 },
    { skill: "React", demand: 85, supply: 82 },
    { skill: "NLP", demand: 88, supply: 45 },
    { skill: "产品规划", demand: 76, supply: 68 },
    { skill: "数据分析", demand: 82, supply: 71 },
    { skill: "大模型", demand: 95, supply: 32 },
  ],
};
